language: python
sudo: true
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  # Install all Python requirements (application and tests)
  - ./test/setup_test.sh
  # To help eventual debug: knowing which exact versions are in use can be rather useful.
  - pip freeze

script:
  # Code dynamic analysis and tests
  - cd test
  # Run test suite with py.test running its coverage plugin
  - pytest --verbose --durations=10 --no-print-logs --cov=alignak_module_nrpe_booster --cov-config .coveragerc test_*.py
  # Report about coverage - Upload coverage results to codecov
  - bash <(curl -s https://codecov.io/bash)
  - cd ..

jobs:
  include:
    - stage: Coding standard
      python: 3.6
      script:
        # Static code analysis
        # -- pycodestyle (former pep8)
        - pycodestyle --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' --ignore='W504' alignak_module_nrpe_booster/*
        # -- pylint
        - pylint --rcfile=.pylintrc -r no alignak_module_nrpe_booster
        # -- pep257
        - pep257 --select=D300 alignak_module_nrpe_booster
    - stage: Pypi deployment
      python: 3.6
      script: echo "Deploying to PyPi..."
      if: (tag IS present)
      deploy:
      - provider: pypi
        distributions: "sdist bdist_wheel"
        skip_existing: true
        on:
          tags: true
        user: alignak
        password:
          secure: "NCdjUEqbgd2Ygneu4TrFT3xCZnLF/t0unTnujUB8Gt+dxEhYZb1j+g2F6HdWLkqm3gM5zk5piAuv7fFSTJFbw2pGoVAuQxkoOP8IA1zGZawnggBT0tLFKblo96tmLxolrciIKtw4Sjh9h1y7lS56wSvlN78GZ5aPg/IQIrKOVHmSrzPNqJ94H9QuRPl5VfOUS+PELzt2mIXZAokCuQiDnZp460MFu5Kg4WUJFfbFtXgi2+JpzBZxnqJWURzgt4BMKVNa6zlh+u1XOmkM0GzXesfYfWTKlfluQ+Ekp+x7LjJPpufgDB9P3wAthE2wlwqpMZTxEr9S+lmOVsA8pWRCByt5AH8BXyDiLF43dqD5ITVgo0BlYrEACMIYBwsALyQOgcu+SjsX88f/VApSEHw1/JoCIQSqc3MH+JkfqZWbUoTpXU7J8v48FdoByqGgkeZ5GCJoFw01Tk+KR1NL/+FA5LghNzl3GcZHCAmdjG3PlDA5yj/FG/jkYQIHRCEb5iOmVTZ9VbcPUg78nnfxfbmjHBvKauyRJ2v1mvsmvOea9Oo3P3JkhDJYkbR1yTrCjehmD99+TpSZoNZG0vuQ/HVhWmBPxwKQVBRd5NoxaJT0g327lOGfSPx5jm/DFY/cpmUxMWWHXhGlrJlV+aYZc8OQvdjpcA2WScUiQwVe9n0uarQ="
    - stage: Debian packaging - Python 2
      python: 2.7
      if: (tag IS blank)
      install:
        # Install packaging requirements
        - echo "Installing packaging requirements..."
        - pip install -r requirements.txt
      script:
        - echo "Packaging for BinTray..."
        - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION deb
      deploy:
      - provider: bintray
        skip_cleanup: true
        file: dist/.bintray-deb.json
        on:
          all_branches: true
        user: mohierf
        key:
          secure: "pwOIRVNK+V4S9L2HgbFIkc3jqjdhucV4CcVF9mYUrFouVp7mH6EkWQBNfVE78rVY3Nj5NUnD0lFswsCr6FqkGAU1VhYaaHFUxboCwFzXfn/ECpy1jseBp/QR1xcHryzdpHW8qAuMOnFvQAH813ND97xjkd4euyXURR05+WmIgajTC8WaYYtq8FLzNc5PEpHrlEeAJDiICbNPVhkk+PPucB7kb7pCptmncx8WDJdyEnzSD0kxFRuY9Nbr/Vl8ttCLkXjo4nxr1nCt3AnkJZwL0qA4c97Do+5Oi/tPM+p5EMPGzWSRJkpuyOyrh0Uh7x9dEKpOJVkv9sxc8Zb2p5ppIJqh+dI47D0OZGyyqT15va5+RqM+PqtIyLAvdENGFZzHRo3EcgggqwDQH0ABc0hoqLeGnmKv45lnNGfsx6vYulUqIvqtLW0N/iQxcsu1LAQSL4OK09pFAkDBk3vkpPrae5BkB8XLZmnejHtFtY4kJH0EHh9kDNexcAHFTw2SGarhVk9bDLaso8xthsol2/fK+ueonmSqEHy65ObXL7q3plvjV0k6fASyGI7rROMikVYvBcChN/ndYsMMzdrhjls/HgOFISY7a1jku8naIT66vI4GQUOdUOFpdTZBH9puW87aEQ+l7Kir5QDP8/fCB7Yna3epedty/ONpV6BOodwdJABn8C4V0b48="
    - stage: Debian packaging - Python 3
      python: 3.6
      if: (tag IS blank)
      install:
        # Install packaging requirements
        - echo "Installing packaging requirements..."
      script:
        - echo "Packaging for BinTray..."
        - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION deb
      deploy:
      - provider: bintray
        skip_cleanup: true
        file: dist/.bintray-deb.json
        on:
          all_branches: true
        user: mohierf
        key:
          secure: "V4S9L2HgbFIkc3jqjdhucV4CcVF9mYUrFouVp7mH6EkWQBNfVE78rVY3Nj5NUnD0lFswsCr6FqkGAU1VhYaaHFUxboCwFzXfn/ECpy1jseBp/QR1xcHryzdpHW8qAuMOnFvQAH813ND97xjkd4euyXURR05+WmIgajTC8WaYYtq8FLzNc5PEpHrlEeAJDiICbNPVhkk+PPucB7kb7pCptmncx8WDJdyEnzSD0kxFRuY9Nbr/Vl8ttCLkXjo4nxr1nCt3AnkJZwL0qA4c97Do+5Oi/tPM+p5EMPGzWSRJkpuyOyrh0Uh7x9dEKpOJVkv9sxc8Zb2p5ppIJqh+dI47D0OZGyyqT15va5+RqM+PqtIyLAvdENGFZzHRo3EcgggqwDQH0ABc0hoqLeGnmKv45lnNGfsx6vYulUqIvqtLW0N/iQxcsu1LAQSL4OK09pFAkDBk3vkpPrae5BkB8XLZmnejHtFtY4kJH0EHh9kDNexcAHFTw2SGarhVk9bDLaso8xthsol2/fK+ueonmSqEHy65ObXL7q3plvjV0k6fASyGI7rROMikVYvBcChN/ndYsMMzdrhjls/HgOFISY7a1jku8naIT66vI4GQUOdUOFpdTZBH9puW87aEQ+l7Kir5QDP8/fCB7Yna3epedty/ONpV6BOodwdJABn8C4V0b48="
    - stage: RPM packaging - Python 2
      python: 2.7
      if: (tag IS blank)
      install:
        # Install packaging requirements
        - echo "Installing packaging requirements..."
        - sudo apt-get install -y rpm
      script:
        - echo "Packaging for BinTray..."
        - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION rpm
      deploy:
      - provider: bintray
        skip_cleanup: true
        file: dist/.bintray-rpm.json
        on:
          all_branches: true
        user: mohierf
        key:
          secure: "V4S9L2HgbFIkc3jqjdhucV4CcVF9mYUrFouVp7mH6EkWQBNfVE78rVY3Nj5NUnD0lFswsCr6FqkGAU1VhYaaHFUxboCwFzXfn/ECpy1jseBp/QR1xcHryzdpHW8qAuMOnFvQAH813ND97xjkd4euyXURR05+WmIgajTC8WaYYtq8FLzNc5PEpHrlEeAJDiICbNPVhkk+PPucB7kb7pCptmncx8WDJdyEnzSD0kxFRuY9Nbr/Vl8ttCLkXjo4nxr1nCt3AnkJZwL0qA4c97Do+5Oi/tPM+p5EMPGzWSRJkpuyOyrh0Uh7x9dEKpOJVkv9sxc8Zb2p5ppIJqh+dI47D0OZGyyqT15va5+RqM+PqtIyLAvdENGFZzHRo3EcgggqwDQH0ABc0hoqLeGnmKv45lnNGfsx6vYulUqIvqtLW0N/iQxcsu1LAQSL4OK09pFAkDBk3vkpPrae5BkB8XLZmnejHtFtY4kJH0EHh9kDNexcAHFTw2SGarhVk9bDLaso8xthsol2/fK+ueonmSqEHy65ObXL7q3plvjV0k6fASyGI7rROMikVYvBcChN/ndYsMMzdrhjls/HgOFISY7a1jku8naIT66vI4GQUOdUOFpdTZBH9puW87aEQ+l7Kir5QDP8/fCB7Yna3epedty/ONpV6BOodwdJABn8C4V0b48="
    - stage: RPM packaging - Python 3
      python: 3.6
      if: (tag IS blank)
      install:
        # Install packaging requirements
        - echo "Installing packaging requirements..."
        - sudo apt-get install -y rpm
      script:
        - echo "Packaging for BinTray..."
        - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION rpm
      deploy:
      - provider: bintray
        skip_cleanup: true
        file: dist/.bintray-rpm.json
        on:
          all_branches: true
        user: mohierf
        key:
          secure: "V4S9L2HgbFIkc3jqjdhucV4CcVF9mYUrFouVp7mH6EkWQBNfVE78rVY3Nj5NUnD0lFswsCr6FqkGAU1VhYaaHFUxboCwFzXfn/ECpy1jseBp/QR1xcHryzdpHW8qAuMOnFvQAH813ND97xjkd4euyXURR05+WmIgajTC8WaYYtq8FLzNc5PEpHrlEeAJDiICbNPVhkk+PPucB7kb7pCptmncx8WDJdyEnzSD0kxFRuY9Nbr/Vl8ttCLkXjo4nxr1nCt3AnkJZwL0qA4c97Do+5Oi/tPM+p5EMPGzWSRJkpuyOyrh0Uh7x9dEKpOJVkv9sxc8Zb2p5ppIJqh+dI47D0OZGyyqT15va5+RqM+PqtIyLAvdENGFZzHRo3EcgggqwDQH0ABc0hoqLeGnmKv45lnNGfsx6vYulUqIvqtLW0N/iQxcsu1LAQSL4OK09pFAkDBk3vkpPrae5BkB8XLZmnejHtFtY4kJH0EHh9kDNexcAHFTw2SGarhVk9bDLaso8xthsol2/fK+ueonmSqEHy65ObXL7q3plvjV0k6fASyGI7rROMikVYvBcChN/ndYsMMzdrhjls/HgOFISY7a1jku8naIT66vI4GQUOdUOFpdTZBH9puW87aEQ+l7Kir5QDP8/fCB7Yna3epedty/ONpV6BOodwdJABn8C4V0b48="
